### ISSUE TITLE
Add counter value in dollars

### ISSUE THREAD

**Issue by Giorgionocera** [bitsongofficial/wallet-dapp#38]
"Where we have space", we need to add the dollar value of the coins. More specifically, "**Nei box grandi inseriamo** il controvalore in dollari, **in tabella**, dove c'è meno spazio, **no**".

![usd-counter-value](https://user-images.githubusercontent.com/13519292/150089655-a9b7a713-99ea-4874-8f0a-8ecba6f4778d.png)

**Comment by DavideSegullo** [comment]
@Giorgionocera Should we use the coingecko API or others? Because the coingecko can have limits.
![image](https://user-images.githubusercontent.com/17269969/150212934-e2d6f1f2-85b7-4869-a76e-0042f78f6bd7.png)

**Comment by Giorgionocera** [comment]
We'll use coingecko.
