### ISSUE TITLE
Add settings

### ISSUE THREAD

**Issue by Giorgionocera** [bitsongofficial/wallet-dapp#39]
We need to add settings for language and currency.
<img width="1558" alt="settings" src="https://user-images.githubusercontent.com/13519292/150090359-ad323da5-b262-4fe1-b4a8-be17500ce0dd.png">

**Comment by DavideSegullo** [comment]
@Giorgionocera what languages and currencies do we plan to include?

**Comment by Giorgionocera** [comment]
As to our plans, we want to provide the following languages:
- English
- Italian
- Spanish
- French (at a later date)
- German (at a later date)
- Indonesian (at a later date)

As for the currencies, we can use all the ones provided by coingeko.
