### ISSUE TITLE
Keybase image loading on bootstrap

### ISSUE THREAD

**Issue by DavideSegullo** [bitsongofficial/wallet-dapp#49]
In the first bootstrap of the application, we spend a lot of time loading the data, this is caused by the calls to keybase. We should contact the keybase services only when we want to consult the list of validators.

![image](https://user-images.githubusercontent.com/17269969/150366393-4433c1a2-71a5-4dde-9493-7b2c0b4dd859.png)

**Comment by Giorgionocera** [comment]
We also updated the code to avoid multiple calls for validators (which caused a useless download of data).
