### ISSUE TITLE
Add disclaimer dialog

### ISSUE THREAD

**Issue by DavideSegullo** [bitsongofficial/wallet-dapp#64]
![image](https://user-images.githubusercontent.com/17269969/151554867-6361abbf-db4b-4b59-aef5-308e03e57661.png)

**Comment by Giorgionocera** [comment]
The text we need to use is the following:

> Before you begin using the BitSong Wallet
> 
> BitSong is a decentralized blockchain ecosystem built for the music industry. The BitSong blockchain and the BitSong wallet are based on public, open-source software. Your use of the BitSong wallet involves various risks, including, but not limited to, financial exposure to the volatility of cryptocurrencies and/or potential misuse of wallet credentials. Blockchain transactions are irreversible and BitSong accepts no liability for any transaction resulting from the use of this wallet. Before using the BitSong wallet, please ensure that you have read and understood all relevant documentation and are satisfied that you accept the risks of investing in digital assets.
