### ISSUE TITLE
Max function shouldn't input 100% of the wallet balance

### ISSUE THREAD

**Issue by ctrl-Felix** [bitsongofficial/wallet-dapp#79]
The current issue with the max function on the delegate and send popup is the fact, that it takes 100% of the wallet balance and so there aren't any more coins to pay the fee. We need something like osmosis has on their IBC deposit, where MAX always lets some funds for the gas.

**Comment by ctrl-Felix** [comment]
Current standard fees in Keplr for 
Delegate/Send: Average - 0.00875 BTSG | High - 0.014 BTSG 
Bridge: Average - 0.0045 BTSG | High - 0.0072 
There is also a max in the proposal deposit dialogue but I am not able to check that one

It might be useful to set max = balance - 0.03 to ensure some dust is in there for the transaction (and maybe even a second transaction). This would be a static approach. Osmosis is doing it a bit more dynamic but I wasn't able to determine exactly how as it seems the percentage is changing with the amount of coins (which makes sense)

**Comment by Giorgionocera** [comment]
Fixed, thank you.
